version: '3'
services:
  postgres-social:
    image: postgres:10.5-alpine
    container_name: postgres_social-3
    volumes:
      - ../postgres-data:/var/lib/postgresqlSocial/data
      - ../dump:/dump
    environment:
      POSTGRES_PASSWORD: Test1234
      POSTGRES_USER: postgres
      POSTGRES_DB: social
    ports:
      - '5432:5432'
    networks:
      - common
networks:
  common:
